version: "3"
services:
  de:
    image: "sparkpos/docker-nginx-php"
    volumes:
      - ~/your-code:/var/www/html 
      - ./php-fpm/fpm-pool.conf:/etc/php/7.1/fpm/pool.d/www.conf
    ports:
      - "9081:80"
    #container_name: de
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.254.0/24
